# Generated by Django 4.2 on 2023-04-04 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Desarrollador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('años_de_exp', models.IntegerField()),
                ('lenguaje', models.CharField(max_length=50)),
                ('framework', models.CharField(max_length=50)),
            ],
        ),
    ]
